#
# System dependent settings 
#
# $Id: make.inc 1123 2006-09-06 12:14:56Z valcke $
#
##### User configurable options #####
#
# Note: The absolute path name must be indicated.
#
# Note: Choose one of these includes files and modify it according to your
#       local settings. Replace the currently active file with your own.
#
include /short/e14/ncj561/now/models/oa3mct/util/make_dir/make.raijin
#
### End User configurable options ###
