#!/usr/bin/perl
# ------------------------------------------------------------------------------
# (C) Crown copyright Met Office. All rights reserved.
# For further details please refer to the file COPYRIGHT.txt
# which you should have received as part of this distribution.
# ------------------------------------------------------------------------------

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";
use FCM::Admin::System qw{
    filter_projects
    get_projects_from_svn_live
    install_svn_hook
};
use FCM::Admin::Util qw{option2config};
use Getopt::Long qw{GetOptions};
use Pod::Usage qw{pod2usage};

main();

sub main {
    my %option;
    my $result = GetOptions(
        \%option,
        q{help|usage|h},
        q{svn-hook-dir=s},
        q{svn-live-dir=s},
        q{svn-project-suffix=s},
    );
    if (!$result) {
        pod2usage(1);
    }
    if (exists($option{help})) {
        pod2usage(q{-verbose} => 1);
    }
    option2config(\%option);
    my @projects = filter_projects([get_projects_from_svn_live()], \@ARGV);
    for my $project (@projects) {
        install_svn_hook($project);
    }
}

__END__

=head1 NAME

fcm-install-svn-hook

=head1 SYNOPSIS

    fcm-install-svn-hook [OPTIONS] [PROJECT ...]

=head1 OPTIONS

=over 4

=item --help, -h, --usage

Prints help and exits.

=item --svn-hook-dir=DIR

Specifies the root location of the directory containing the source files of the
hook scripts. See L<FCM::Admin::Config|FCM::Admin::Config> for the current
default.

=item --svn-live-dir=DIR

Specifies the root location of the live directory. See
L<FCM::Admin::Config|FCM::Admin::Config> for the current default.

=item --svn-project-suffix=NAME

Specifies the suffix added to the project name. The default is "_svn".

=back

=head1 ARGUMENTS

=over 4

=item PROJECT

Specifies one or more project requiring hooks scripts to be installed. If no
project is specified, the program install the hook scripts to all projects in
the live directory.

=back

=head1 DESCRIPTION

This program install hook scripts for Subversion repositories in the live
directory.

=head1 COPYRIGHT

E<169> Crown copyright Met Office. All rights reserved.

=cut
